- hosts: localhost
  become: true
  vars_files:
    - users.yml
  tasks:
    - name: Add Users and update passwords
      vars:
        password: "{{ lookup('password', './password-{{ item.name }}' ' length=6')  }}"
#        password: "{{ lookup('password', './password-{{ item.name }}' ' length=6')  }}"
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
      with_items:
        - "{{ myusers }}"
